version: '3'
services:
  web:
    build: .
    container_name: zzzcalc
    working_dir: /usr/local/apache2/htdocs
    volumes:
      - ./public-html:/usr/local/apache2/htdocs
    ports:
      - "8080:8080"

volumes:
  pgdata: